spring:
  shell:
    interactive:
      enabled: true
  data:
    jpa:
      repositories:
        enabled: true

logging:
  level:
    root: INFO
    org:
      springframework:
        jdbc: TRACE
        transaction: TRACE
        orm:
          jpa: TRACE
      postgres: TRACE

custom:
  first:
    url: jdbc:postgresql://localhost:5432/playground?currentSchema=example
    username: postgres
    password: password
  second:
    url: jdbc:postgresql://localhost:5432/playground?currentSchema=example
    username: postgres
    password: password
